name: pull-workflow

on:
  pull_request:
    branches: [main]
    types: [closed, opened]

concurrency:
  group: pull-ci-${{ github.event.pull_request.number }}
  cancel-in-progress: false

jobs:
  pr_close_job:
    runs-on: self-hosted
    environment: Test
    steps:
      - uses: actions/checkout@v2

      - name: Debug Event Details
        run: |
          echo "Pull Request Number: ${{ github.event.pull_request.number }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Action: ${{ github.event.action }}"

      - name: Make build script executable
        run: chmod +x ${CI_DIR}/build.sh

      - name: Run build script on pull request close
        if: ${{ github.event.action == 'closed' }}
        run: bash ${CI_DIR}/build.sh

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CI_DIR: "/Users/t-laode.ika/Documents/githubAction/cicd"

  trigger_push_workflow:
    needs: pr_close_job
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'closed' }}
    steps:
      - name: Trigger push-reusable workflow
        uses: actions/checkout@v2

      - name: Trigger Reusable Workflow
        uses: actions/github-script@v6
        with:
          script: |
            const { github, context } = require('@actions/github');
            const response = await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'push-reusable.yml',  # Call reusable workflow
              ref: 'main',  # Main branch
            });
            console.log(response);
