name: pull-review-workflow

on:
  deployment

jobs:
  pr_review_requested_job:
    # Runs only when a review is requested
    runs-on: self-hosted
    if: github.event.action == 'deployment'
    steps:
      - uses: actions/checkout@v2

      - name: Debug Event Details
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Action: ${{ github.event.action }}"
          echo "The deployment need to be reviewed."

      - name: Make build script executable
        run: chmod +x ${CI_DIR}/build.sh

      - name: Run build script
        run: bash ${CI_DIR}/build.sh

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO_MESSAGE: ${{ github.event.number }} ${{ github.event.pull_request.title }}
      CI_DIR: "/home/applmgr/cicd"
