name: pull-workflow

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  pull_request_job:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Debug Event Details
        run: |
          echo "Event Action: ${{ github.event.action }}"
          echo "PR Merged: ${{ github.event.pull_request.merged }}"
