name: pull-workflow

on:
  pull_request:
    branches: [devTest]
    types: [closed]

# Concurrency lock for the specific pull request
concurrency:
  group: pull-ci-${{ github.event.pull_request.number }}  # Unique to the PR
  cancel-in-progress: false  # Queue subsequent jobs instead of canceling

jobs:
  pr_close_job:
    runs-on: self-hosted
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2

      - name: Debug Event Details
        run: |
          echo "Pull Request Number: ${{ github.event.pull_request.number }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Action: ${{ github.event.action }}"
          if [ "${{ github.event.pull_request.merged }}" = "true" ]; then
            echo "The PR was merged."
          else
            echo "The PR was not merged."
          fi

      - name: Make build script executable
        run: chmod +x ${CI_DIR}/build.sh

      - name: Run build script
        run: bash ${CI_DIR}/build.sh

      # Add a step to configure Git
      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
      - name: Cherry-pick changes from devTest
        run: |
          git fetch origin
          git checkout prodTest
          # Cherry-pick the changes from the merged PR
          PR_COMMIT_SHA="${{ github.event.pull_request.merge_commit_sha }}"
          git cherry-pick $PR_COMMIT_SHA || { echo "Cherry-pick failed!"; exit 1; }

      - name: Push changes to prodTest
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/alif5623/cidcdTest.git
          git push origin prodTest

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Merge changes from devTest"
          body: "This pull request includes changes from the devTest branch."
          base: prodTest
          head: prodTest
          token: ${{ secrets.GITHUB_TOKEN }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO_MESSAGE: ${{ github.event.number }} ${{ github.event.pull_request.title }}
      CI_DIR: "/Users/t-laode.ika/Documents/githubAction/cicd"
