name: pull-workflow

on:
  pull_request:
    branches: [main]
    types: [closed, opened]

concurrency:
  group: pull-ci-${{ github.event.pull_request.number }}
  cancel-in-progress: false

jobs:
  pr_close_job:
    runs-on: self-hosted
    environment: Test
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2

      - name: Debug Event Details
        run: |
          echo "Pull Request Number: ${{ github.event.pull_request.number }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Action: ${{ github.event.action }}"
          if [ "${{ github.event.pull_request.merged }}" = "true" ]; then
            echo "The PR was merged."
          else
            echo "The PR was not merged."
          fi
      - name: Make build script executable
        run: chmod +x ${CI_DIR}/build.sh

      - name: Run build script
        run: bash ${CI_DIR}/build.sh
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CI_DIR: "/Users/t-laode.ika/Documents/githubAction/cicd"
