name: pull-workflow

on:
  pull_request:
    branches: [main]
    types: [closed]

# Concurrency group ensures pull requests are handled one at a time
concurrency:
  group: ci-${{ github.event.pull_request.number }}  # Unique to the PR number
  cancel-in-progress: false  # Queue subsequent jobs, don't cancel them

jobs:
  pr_close_job:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Debug Event Details
        run: |
          echo "Pull Request Number: ${{ github.event.pull_request.number }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Action: ${{ github.event.action }}"

      - name: Make build script executable
        run: chmod +x ${CI_DIR}/build.sh

      - name: Run build script on pull request close
        run: bash ${CI_DIR}/build.sh

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO_MESSAGE: ${{ github.event.number }} ${{ github.event.pull_request.title }}
      CI_DIR: "/Users/t-laode.ika/Documents/githubAction/cicd"
      TVLK_TOP: "/Users/t-laode.ika/TVLK_TOP"
