name: pull-workflow

on:
  pull_request:
    branches: [devTest]
    types: [closed]

# Concurrency lock for the specific pull request
concurrency:
  group: pull-ci-${{ github.event.pull_request.number }}  # Unique to the PR
  cancel-in-progress: false  # Queue subsequent jobs instead of canceling

jobs:
  pr_close_job:
    runs-on: self-hosted
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2

      - name: Debug Event Details
        run: |
          echo "Pull Request Number: ${{ github.event.pull_request.number }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Action: ${{ github.event.action }}"
          if [ "${{ github.event.pull_request.merged }}" = "true" ]; then
            echo "The PR was merged."
          else
            echo "The PR was not merged."
          fi

      - name: Make build script executable
        run: chmod +x ${CI_DIR}/build.sh

      - name: Run build script
        run: bash ${CI_DIR}/build.sh

      # Add a step to configure Git
      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      # Add a step to commit changes (if any)
      - name: Commit changes
        run: |
          cd /Users/t-laode.ika/Documents/localCICD/cidcdTest
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/alif5623/cidcdTest.git
          git checkout prodTest
          git add .
          git commit -m "Auto-commit: Update to STG after PR merge" || echo "No changes to commit"

      # Add a step to push changes to another branch (e.g., `target-branch`)
      - name: Push to target branch
        run: |
          git push
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO_MESSAGE: ${{ github.event.number }} ${{ github.event.pull_request.title }}
      CI_DIR: "/Users/t-laode.ika/Documents/githubAction/cicd"
