name: pull-workflow

on:
  pull_request:
    branches: [devTest]
    types: [closed]

# Concurrency lock for the specific pull request
concurrency:
  group: pull-ci-${{ github.event.pull_request.number }}  # Unique to the PR
  cancel-in-progress: false  # Queue subsequent jobs instead of canceling

jobs:
  pr_close_job:
    if: ${{ github.event.pull_request.merged }}
    runs-on: self-hosted
    environment: ID02-STG-Environment
    steps:
      - uses: actions/checkout@v2

      - name: Debug Event Details
        run: |
          echo "Pull Request Number: ${{ github.event.pull_request.number }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Action: ${{ github.event.action }}"

      - name: Make build script executable
        run: chmod +x ${CI_DIR}/build.sh

      - name: Run build script on pull request close
        run: bash ${CI_DIR}/build.sh

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO_MESSAGE: ${{ github.event.number }} ${{ github.event.pull_request.title }}
      CI_DIR: "/home/applmgr/cicd"
