name: push-reusable-workflow

on:
  workflow_run:
    workflows: ["pull-workflow"]
    types:
      - completed

jobs:
  push_job:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.pull_requests[0].state == 'closed' }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Debug Event Details
        run: |
          echo "Pull Request Number: ${{ github.event.workflow_run.pull_requests[0].number }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Action: ${{ github.event.action }}"

      - name: Make build script executable
        run: chmod +x ${CI_DIR}/build.sh

      - name: Run build script on push
        run: bash ${CI_DIR}/build.sh

      - name: Clone & Commit Repository
        run: |
          git clone https://user:$GITHUB_TOKEN@github.com/alif5623/cidcdTest.git
          cd cidcdTest
          git config user.name "alif5623"
          git config user.email "laode.alif@ui.ac.id"
          git checkout -b devTest
          git add .
          git commit -m "Update branch"

      - name: Push to prod Repo
        run: |
          git remote set-url origin https://user:$GITHUB_TOKEN@github.com/alif5623/cidcdTest.git
          git push origin devTest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CI_DIR: "/Users/t-laode.ika/Documents/githubAction/cicd"
