name: push-reusable-workflow

on:
  workflow_run:
    workflows: ["pull-workflow"]
    types:
      - completed

jobs:
  push_job:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.pull_requests[0].state == 'closed' }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Debug Event Details
        run: |
          echo "Pull Request Number: ${{ github.event.workflow_run.pull_requests[0].number }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Action: ${{ github.event.action }}"

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CI_DIR: "/Users/t-laode.ika/Documents/githubAction/cicd"
