name: push-merge-workflow

on:
  push:
    branches: ["prodTest"]

jobs:
  push_job:
    runs-on: self-hosted
    environment: Test
    steps:
      - uses: actions/checkout@v2

      - name: Debug Event Details
        run: |
          echo "Pull Request Number: ${{ github.event.workflow_run.pull_requests[0].number }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Action: ${{ github.event.action }}"
          echo "The PR was merged."

      - name: Make build script executable
        run: chmod +x ${CI_DIR}/build.sh

      - name: Run build script on push
        run: bash ${CI_DIR}/build.sh || echo "Build script failed, but proceeding."

      - name: Debug Build Script Status
        run: echo "Build script completed, moving to next steps."

      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Commit changes
        run: |
          cd /Users/t-laode.ika/Documents/localCICD/cidcdTest
          git checkout prodTest
          git add .
          git commit -m "Auto-commit: Update to STG after PR merge" || echo "No changes to commit"

      - name: Push to target branch
        run: git push origin prodTest || echo "Push failed, but proceeding."

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO_MESSAGE: ${{ github.event.workflow_run.pull_requests[0].title }}
      CI_DIR: "/Users/t-laode.ika/Documents/githubAction/cicd"
