name: push-workflow

on:
  workflow_run:
    workflows: [pull-workflow]
    types: [completed]
  push:
    branches: [main]
jobs:
  push_job:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Debug Event Details
        run: |
          echo "Event Action: ${{ github.event.action }}"
          echo "PR Pushed"
