name: push-workflow

on:
  workflow_run:
    workflows: ["pull-workflow"]
    types:
      - completed

# Use the same global concurrency lock to enforce strict order
concurrency:
  group: global-ci  # Global concurrency lock across all workflows
  cancel-in-progress: false  # Queue subsequent jobs instead of canceling

jobs:
  push_job:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Debug Event Details
        run: |
          echo "Pull Request Number: ${{ github.event.workflow_run.pull_requests[0].number }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Action: ${{ github.event.action }}"

      - name: Make build script executable
        run: chmod +x ${CI_DIR}/build.sh

      - name: Run build script on push
        run: bash ${CI_DIR}/build.sh

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO_MESSAGE: ${{ github.event.number }} ${{ github.event.head_commit.message }}
      CI_DIR: "/Users/t-laode.ika/Documents/githubAction/cicd"
      TVLK_TOP: "/Users/t-laode.ika/TVLK_TOP"
