name: push-workflow

on:
  workflow_run:
    branches: ["prodTest"]
    workflows: ["pull-workflow"]
    types:
      - completed

# Concurrency lock for the specific pull request to ensure strict ordering
concurrency:
  group: push-ci-${{ github.event.workflow_run.pull_requests[0].number }}  # Unique to the PR
  cancel-in-progress: false  # Queue subsequent jobs instead of canceling

jobs:
  push_job:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Debug Event Details
        run: |
          echo "Pull Request Number: ${{ github.event.workflow_run.pull_requests[0].number }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Action: ${{ github.event.action }}"
          echo "The PR was merged."

      - name: Make build script executable
        run: chmod +x ${CI_DIR}/build.sh

      - name: Run build script on push
        run: bash ${CI_DIR}/build.sh

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO_MESSAGE: ${{ github.event.workflow_run.pull_requests[0].title }}
      CI_DIR: "/Users/t-laode.ika/Documents/githubAction/cicd"
